In [348]:
import pandas as pd
import numpy as np
import random as rnd

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.preprocessing import Imputer
from sklearn import preprocessing

In [349]:
train_df = pd.read_csv('data/train.csv')
predict_df = pd.read_csv('data/test.csv')


display(train_df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5000,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [350]:
#data processing
print(train_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB
None

In [351]:
train_df['Age_interv']=pd.cut(train_df['Age'],20)
predict_df['Age_interv']=pd.cut(predict_df['Age'],20)

train_df=pd.get_dummies(train_df,columns=['Sex','Embarked', 'Age_interv', 'SibSp','Parch','Ticket'])
predict_df=pd.get_dummies(predict_df,columns=['Sex','Embarked', 'Age_interv', 'SibSp','Parch','Ticket'])

y=train_df['Survived'].values
train_df=train_df.drop(['Fare','PassengerId', 'Survived','Name','Cabin','Age'], axis=1)
predict_df=predict_df.drop(['Fare','PassengerId','Name','Cabin','Age'], axis=1)

In [352]:

display(train_df)
X = train_df.values
X_predict=predict_df.values
print(X)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Columns: 721 entries, Pclass to Ticket_WE/P 5735
dtypes: int64(1), uint8(720)
memory usage: 633.5 KB
None

,Pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,"Age_interv_(0.34, 4.399]","Age_interv_(4.399, 8.378]","Age_interv_(8.378, 12.357]","Age_interv_(12.357, 16.336]",...,Ticket_STON/O2. 3101290,Ticket_SW/PP 751,Ticket_W./C. 14258,Ticket_W./C. 14263,Ticket_W./C. 6607,Ticket_W./C. 6608,Ticket_W./C. 6609,Ticket_W.E.P. 5734,Ticket_W/C 14208,Ticket_WE/P 5735
0,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,3,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,3,0,1,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,2,1,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,3,1,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,3,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15,2,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,3,0,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,2,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,3,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,2,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,2,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,3,1,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
23,1,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,3,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
25,3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,3,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,1,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,3,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,2,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
862,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
863,3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
864,2,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
865,2,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
866,2,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
867,1,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
868,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
869,3,0,1,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
870,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
871,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
872,1,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
873,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
874,2,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
875,3,1,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
876,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
877,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
878,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
879,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
880,2,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
881,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
882,3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
883,2,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
884,3,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
885,3,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
886,2,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
887,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
888,3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
889,1,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
890,3,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

[[3 0 1 ..., 0 0 0]
 [1 1 0 ..., 0 0 0]
 [3 1 0 ..., 0 0 0]
 ...,
 [3 1 0 ..., 0 0 0]
 [1 0 1 ..., 0 0 0]
 [3 0 1 ..., 0 0 0]]

In [355]:
print(train_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Columns: 721 entries, Pclass to Ticket_WE/P 5735
dtypes: int64(1), uint8(720)
memory usage: 633.5 KB
None

In [356]:
print(predict_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Columns: 404 entries, Pclass to Ticket_W.E.P. 5734
dtypes: int64(1), uint8(403)
memory usage: 167.8 KB
None

In [353]:
#start learning
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=.1, random_state=42)
classifiers = [LogisticRegression(tol=0.000001),
               KNeighborsClassifier(),
               SVC(kernel="linear", C=0.025),
               SVC(gamma=2, C=1),
               GaussianProcessClassifier(),
               DecisionTreeClassifier(),
               RandomForestClassifier(),
               MLPClassifier(),
               MLPClassifier(hidden_layer_sizes=(100,100)),
               AdaBoostClassifier(),
               GaussianNB(),
               QuadraticDiscriminantAnalysis()]
res=[]
mxscore=0
for clf in classifiers:
    clf.fit(X_train, y_train)
    score = clf.score(X_test, y_test)
    print(score)
    print(clf)
    if score>mxscore: 
        optimclf=clf
        mxscore=score
    res.append((score,clf))

0.844444444444
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=1e-06,
          verbose=0, warm_start=False)
0.833333333333
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
0.811111111111
SVC(C=0.025, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.611111111111
SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=2, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.833333333333
GaussianProcessClassifier(copy_X_train=True, kernel=None,
             max_iter_predict=100, multi_class='one_vs_rest', n_jobs=1,
             n_restarts_optimizer=0, optimizer='fmin_l_bfgs_b',
             random_state=None, warm_start=False)
0.866666666667
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
0.855555555556
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
0.844444444444
MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)
0.833333333333
MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 100), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)
0.822222222222
AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)
0.533333333333
GaussianNB(priors=None)
0.666666666667
QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
               store_covariance=False, store_covariances=None, tol=0.0001)

/home/janniklas/.local/lib/python3.5/site-packages/sklearn/discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

In [354]:
out=optimclf.predict(X_predict)
dfout=pd.DataFrame(data={'PassengerId': predict_df['PassengerId'].values, 'Survived': out})
dfout.to_csv('out.csv',index=False)

ValueError: Number of features of the model must match the input. Model n_features is 721 and input n_features is 404